// Given a string, WAM to return all its subsequences in an arraylist.
// A String is a subsequence of a given String that is generated by deleting some character of a given string without changing its order.

// OR

// Given a string, write a method to print all its subsequences.

package Week_10_Recursion.Extra_Practice;

import java.util.ArrayList;
import java.util.Scanner;

public class Subsequences {

    // Function to generate all subsequences of a given string
    public static ArrayList<String> generateSubsequences(String input) {
        ArrayList<String> subsequences = new ArrayList<>();

        // Base case: if the string is empty, add an empty string to the list
        if (input.isEmpty()) {
            subsequences.add("");
            return subsequences;
        }

        // Get the first character of the string
        char firstChar = input.charAt(0);

        // Recursively find subsequences of the rest of the string
        ArrayList<String> smallerSubsequences = generateSubsequences(input.substring(1));

        // Add subsequences with and without the first character
        for (String subSeq : smallerSubsequences) {
            subsequences.add(subSeq);             // subsequence without firstChar
            subsequences.add(firstChar + subSeq); // subsequence with firstChar
        }

        return subsequences;
    }

    // Function to print all subsequences of a given string
    public static void printSubsequences(String input, String current) {
        // Base case: when the string is empty, print the current subsequence
        if (input.isEmpty()) {
            System.out.println(current);
            return;
        }

        // Recursively generate subsequences with and without the first character
        printSubsequences(input.substring(1), current + input.charAt(0));
        printSubsequences(input.substring(1), current);
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        // Prompt the user to enter a string
        System.out.print("Enter a string to find its subsequences: ");
        String userInput = scanner.nextLine();

        // Generate and print all subsequences using ArrayList
        ArrayList<String> subsequences = generateSubsequences(userInput);
        System.out.println("All possible subsequences of the string \"" + userInput + "\" using ArrayList are: " + subsequences);

        // Print all subsequences directly using recursive printing
        System.out.println("All possible subsequences of the string \"" + userInput + "\" using direct printing are:");
        printSubsequences(userInput, "");
    }
}
